// <auto-generated />
using System;
using BackendData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240819094555_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BackendData.DomainModels.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            Rating = 2,
                            Url = "https://blog1.com"
                        },
                        new
                        {
                            BlogId = 2,
                            Rating = 3,
                            Url = "https://blog2.com"
                        },
                        new
                        {
                            BlogId = 3,
                            Rating = 1,
                            Url = "https://blog3.com"
                        },
                        new
                        {
                            BlogId = 4,
                            Rating = 3,
                            Url = "https://blog5.com"
                        });
                });

            modelBuilder.Entity("BackendData.DomainModels.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 1,
                            Content = "Dette er Post 1 i Blog 1",
                            Rating = 2,
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 1,
                            Content = "Dette er Post 2 i Blog 1",
                            Rating = 3,
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            BlogId = 1,
                            Content = "Dette er Post 3 i Blog 1",
                            Rating = 4,
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            BlogId = 2,
                            Content = "Dette er post 4 i Blog 2",
                            Rating = 3,
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            BlogId = 2,
                            Content = "Dette er post 5 i Blog 2",
                            Rating = 1,
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            BlogId = 3,
                            Content = "Dette er post 6 i Blog 3",
                            Rating = 2,
                            Title = "Post 6"
                        });
                });

            modelBuilder.Entity("BackendData.DomainModels.Post", b =>
                {
                    b.HasOne("BackendData.DomainModels.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("BackendData.DomainModels.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
