// <auto-generated />
using System;
using BackendData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BackendData.DomainModels.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            AccountNumber = "123-3452134543-32",
                            Rating = 2,
                            Url = "https://blog1.com"
                        },
                        new
                        {
                            BlogId = 2,
                            AccountNumber = "123-9384613085-55",
                            Rating = 3,
                            Url = "https://blog2.com"
                        },
                        new
                        {
                            BlogId = 3,
                            AccountNumber = "117-5384643035-94",
                            Rating = 1,
                            Url = "https://blog3.com"
                        },
                        new
                        {
                            BlogId = 4,
                            AccountNumber = "118-1354643035-77",
                            Rating = 3,
                            Url = "https://blog5.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
