@NewIdentityApiDemo_HostAddress = https://localhost:7088

GET {{NewIdentityApiDemo_HostAddress}}/weatherforecast/
Accept: application/json

###

POST  {{NewIdentityApiDemo_HostAddress}}/identity/register
Content-Type: application/json
Accept: application/json

{
"userName": "admin",
"email": "admin@example.com",
"password": "Passw0rd!"
}

###

POST  {{NewIdentityApiDemo_HostAddress}}/identity/login
Content-Type: application/json
Accept: application/json

{
"email": "admin@example.com",
"password": "Passw0rd!"
}

###

GET {{NewIdentityApiDemo_HostAddress}}/weatherforecast/
Authorization: Bearer CfDJ8FBoSKsLfPxOsodcLZnGbU9ACT0JuZBrfmQn0qGTmR-d4Q7NUCs3dUTNEGfG9V6m2MytzhZMBxTivYKaZMIlgS5FUmWklhxdMmDi1RdnUTc6e_KTfeQ7GB-JFkbA_AHCaouywEUEGJ1slhztBMcFPmHhnkgiQyD6PoNAVcUTDFV-2l8A85iBOZLAGnzPtsGQER9xKagefv_eRvgEWK8CJppQOBr2hFkeoMTlpi_3-nFUtU_Hqb7TOz52fn1_Uo9qWa-mxsoNwbeN0Tb3XGsMKv2kqQbPH7CEHbO_ZAEj3bfAYMaJzr0MkgZtEEzSe9kNR0Gv-uDAgSZkuGpqYVJ-qP3Z1b1pAsif-kzte4zch0a5XsdXHKKHBudAfAucZegrzfqKX5KlguFDGry76QZwfxfsDiLg678dIUfY9EhBUCOt0BhVnlIUUrpAxFvpm-pwRt0cZgH2U_iVzEPm6zStftxkxuu4UBvGe14adHFT8CuYkuWIk-Yf9ayJqngBJ_10W1p8a6TSc5mM5VPBnBS3Cs7gv7VxS0hQr5HdDlbKlPYIQdOoxv8CnwTJNJP6qofBYG3-c6E9wxPlBUVyzzF9hPvrepwkAgdqfPPh_ODJad8zXbiOY0yH4FPtHkuAoEkOm51afe9hWf9A3jlTWRppL6F-Rzq3wT1_tmipoR5dzn_uhYVWRQKr-758r_jDZayIyw