@NewIdentityApiDemo_HostAddress = https://localhost:7088

GET {{NewIdentityApiDemo_HostAddress}}/weatherforecast/
Accept: application/json

###

POST  {{NewIdentityApiDemo_HostAddress}}/identity/register
Content-Type: application/json
Accept: application/json

{
"userName": "admin",
"email": "admin@example.com",
"password": "Passw0rd!"
}

###

POST  {{NewIdentityApiDemo_HostAddress}}/identity/login
Content-Type: application/json
Accept: application/json

{
"email": "admin@example.com",
"password": "Passw0rd!"
}

###

GET {{NewIdentityApiDemo_HostAddress}}/weatherforecast/
Authorization: Bearer CfDJ8FBoSKsLfPxOsodcLZnGbU_0vE-aZ_0U9HKeATa30bE7bj0u0WqO9szkkp4ZyxNrffrrXVeh85bmVFm9oAQ3Mr5MgGlJPL3-KZHXOCMr_Ene26-VuLgBE7NDvzyqJr98PWyCmYV505ZTTqnHO_g0OOE_BfTX3GyjeQeRjFdlt7_-mhXnZYvM72QHu4J1X90qelAZ4DspGuSZ_j1_xMFq2fJsEfzwHC1D0rNBT_CVD9x0Rc4oDXB2gG7tLgVMY3TITTBvjL3V5OSx7E_BEtKOmQgOlEBU_rIYdJaoRpT8isznqRRrIWnpMaD-fpG2dU0E6ACmiDdSXPa_MqeR0fh57Wg393P6lkDZfatHZCGMg3e1DLHrBO5wRy1zRxpzhoh-CsrZdOyaNW3mvSk_YOCjRHA30rJXEpA7PLM1vucd-kKnONYdTSinlEXH4Erde5GUKv7BZa3S-t7qvfgJ1jz1_aaYpcbB_nZK2Z-h3AIEtHP2KC3PFY1gbNeDOAEopRCf4xQj-SqiIoh6XOhNyWI9RUAiL6EMw7JVXDRsLzqyBgUeWhAbkQ6HqQzeoWUqpBzWfOsXere3lko1zCjcgVnv-lhXUAc_IUqNPFMYBMHZieDvGaECQeYB7Fs0b0x5MliJ1jgbJRpz_WrvSfuG1EcPmg0GwdNFUlCCV14W_Yv3ATn5VdDJALJYvSbORGdvEpG4yQ