@ContentNegotiation_HostAddress = https://localhost:7118

# Accept XML
GET {{ContentNegotiation_HostAddress}}/api/blog
Accept: application/xml

###

# Text Content Type (406 Not Acceptable if Content is Json)
GET {{ContentNegotiation_HostAddress}}/api/blog
Accept: text/plain

###

GET {{ContentNegotiation_HostAddress}}/api/blog
Accept: application/csv