@ModelStateValidation_HostAddress = https://localhost:7021

# Demo af manglende Title og forkert format for ISBN
POST {{ModelStateValidation_HostAddress}}/api/Books/
Content-Type: application/json
Accept: application/json

{
    "Description": "Book description",
    "ISBN": "123456789"
}

###

# Demo af manual validation rule
POST {{ModelStateValidation_HostAddress}}/api/Books/
Content-Type: application/json
Accept: application/json

{
    "Title": "Book title",
    "Description": "Book description",
    "ISBN": "1234567891234"
}
