// <auto-generated />
using System;
using BackendData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240819101209_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BackendData.DomainModels.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            Rating = 2,
                            Url = "https://blog1.com"
                        },
                        new
                        {
                            BlogId = 2,
                            Rating = 3,
                            Url = "https://blog2.com"
                        },
                        new
                        {
                            BlogId = 3,
                            Rating = 1,
                            Url = "https://blog3.com"
                        },
                        new
                        {
                            BlogId = 4,
                            Rating = 3,
                            Url = "https://blog5.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
