// <auto-generated />
using BackendData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("BackendData.DomainModels.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluralsightUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterAlias")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "Martin Fowler",
                            PluralsightUrl = "https://app.pluralsight.com/profile/martin-fowler",
                            TwitterAlias = "https://twitter.com/martinfawler"
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "Eric Evans",
                            PluralsightUrl = "https://app.pluralsight.com/profile/eric-evans",
                            TwitterAlias = "https://twitter.com/ericevans"
                        },
                        new
                        {
                            AuthorId = 3,
                            Name = "Steve Smith",
                            PluralsightUrl = "https://app.pluralsight.com/profile/steve-smith",
                            TwitterAlias = "https://twitter.com/stevesmith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
